packaging_format = 2

id = "bozon"
name = "BoZoN"
description.en = "Minimalist Drag & drop file sharing app"
description.fr = "Application minimaliste de partage de fichiers"

version = "2.4.18~ynh3"

maintainers = ["ewilly"]

[upstream]
license = "AGPL-3.0"
code = "https://github.com/broncowdd/BoZoN"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/bozon"

    [install.init_main_permission]
    type = "group"
    default = false

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/broncowdd/BoZoN/archive/ce0265e0dd13bc1e3cbbf0d96b846f65d1a17173.zip"
        sha256 = "42e8e81771cb3489297a75138a69cf83c82edc3e6ea5988b8d436254ac502b1b"
        autoupdate.upstream = "https://github.com/broncowdd/BoZoN"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["uploads", "thumbs"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-zip php8.2-curl php8.2-gd"
