#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "bozon"
name = "BoZoN"
description.en = "Minimalist Drag & drop file sharing app"
description.fr = "Application minimaliste de partage de fichiers"

version = "2.4.18~ynh4"

maintainers = ["ewilly"]

[upstream]
license = "AGPL-3.0"
code = "https://github.com/broncowdd/BoZoN"

[integration]
yunohost = ">= 4.3.0"
architectures = "all"
multi_instance = false
ldap = true
sso = "not_relevant"
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/bozon"

    [install.init_main_permission]
    help.en = "If public, any visitor can convert audio or video files using your server."
    help.fr = "Si l’application est publique, n’importe quel visiteur pourra utiliser votre serveur pour convertir des fichiers audio et vidéos."
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://github.com/broncowdd/BoZoN/archive/ce0265e0dd13bc1e3cbbf0d96b846f65d1a17173.zip"
    sha256 = "42e8e81771cb3489297a75138a69cf83c82edc3e6ea5988b8d436254ac502b1b"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["uploads", "thumbs"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php7.4-fpm",
        "php7.4-zip",
        "php7.4-curl",
        "php7.4-gd",
    ]
