#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    test_upgrade_from.8fcdd9d4e05b1d5e4f98dd57ac3659c060330916.name = "Use official helper"
